version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    versioning-strategy: lockfile-only
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 20
    labels:
      - 'dependencies'
      - 'automerge'
