version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'weekly'
      time: '07:00'
    open-pull-requests-limit: 20
    labels:
      - 'dependencies'
      - 'automerge'
